### PR TITLE
Create william.json

### PR DESCRIPTION
**Pull request by wdhdev**

### CODE REVIEW

**Review by omsenjalia — APPROVED** [review]
Thanks for opening this pr. I am sorry it took alot of time to get reviewed

**Comment by omsenjalia** [comment]
your changes should be made in a few minutes

**Comment by wdhdev** [comment]
No problem

**Comment by omsenjalia** [comment]
Screenshot_20220817-093546_Brave

Do you want dns only or proxies with cf

**Comment by omsenjalia** [comment]
Proxied*

**Comment by wdhdev** [comment]
> Screenshot_20220817-093546_Brave
> 
> Do you want dns only or proxies with cf

DNS only

**Comment by omsenjalia** [comment]
Alright

**Pull request merged**
