### PR TITLE
Create www.json

### PR DESCRIPTION
**Pull request by wdhdev**

### CODE REVIEW

**Comment by omsenjalia** [comment]
www?

**Comment by omsenjalia** [comment]
You should get www.william.uses.cf

**Comment by wdhdev** [comment]
You should redirect www.uses.cf to uses.cf

**Comment by wdhdev** [comment]
> You should get [www.william.uses.cf](http://www.william.uses.cf)

Not needed for subdomains

**Comment by omsenjalia** [comment]
> You should redirect [www.uses.cf](http://www.uses.cf) to uses.cf

Alright I'll do something about it. If you want you can get www.william.uses.cf

**Pull request closed without merging**
